language: php
php:
  - 7.2
env:
  - APP_ENV=testing APP_KEY=base64:pnyKvyuVHrNCGNsnmRvxWPY7ScmwUimwvrtrJyhfAKc=
before_script:
  - touch database/testing.database.sqlite
  - composer self-update
  - composer install --no-interaction --optimize-autoloader
  - bin/reinstall.sh
  - php artisan passport:install
script: vendor/bin/phpunit
